version: "3.8"
networks:
  laravel:

services:
  database:
    image: postgres:16.2-alpine3.19
    container_name: database
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alumno
      POSTGRES_PASSWORD: alumno
    volumes:
      - database-disk-dungeonMaker:/var/lib/postgresql/data
      - ./initdb.d/:/docker-entrypoint-initdb.d
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - laravel

  web:
    depends_on:
      - php
      - database
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    networks:
      - laravel
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alumno@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: alumno
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-disk-dungeonMaker:/var/lib/pgadmin
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
    container_name: php
    ports:
      - "9000:9000"

volumes:
  database-disk-dungeonMaker:
  pgadmin-disk-dungeonMaker:
